#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

touch stratification.foam
runApplication blockMesh
restore0Dir
runApplication setFields

# runApplication $(getApplication)
runApplication decomposePar
runParallel $(getApplication)

#------------------------------------------------------------------------------
