#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

restore0Dir
touch AMR.foam
runApplication blockMesh
runApplication setFields

runApplication $(getApplication)

#------------------------------------------------------------------------------
