#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication ./Allrun.pre

#-- Run on single processor
#runApplication $(getApplication)

# Decompose
runApplication decomposePar -allRegions

# Run
runParallel $(getApplication)

# Reconstruct
runApplication reconstructPar -allRegions

#------------------------------------------------------------------------------
