#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
restore0Dir
runApplication setFields
# Make .foam file

touch "${PWD##*/}.foam"
runApplication decomposePar
runParallel $(getApplication)
